# Deploy wizard-almanac app on production env
services:
  wizard-almanac:
    # set image version with env variable
    image: ${COMPANY_CONTAINER_REGISTRY}/wizard-almanac:${APP_VERSION}
    ports:
    # publish app port 5000 to the host's port 5000
      - "0.0.0.0:5000:5000"
    environment:
    #The credential to access database might be passed to the container by setting the DATABASE_CREDENTIAL_FILE parameter when run pipeline. If this is not set, an empty file is passed to DATABASE_CREDENTIAL_FILE variable
      - DATABASE_CREDENTIAL_FILE